apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devcontainer-pipeline-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devcontainer-pipeline-service
    app.kubernetes.io/part-of: pipeline-service
  name: devcontainer-pipeline-service
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: devcontainer-pipeline-service
    weight: 100
status: {}
